server:
   port: 8888
spring:
   cloud:
      config:
         server:
           git:
            default-label: master
            uri: https://github.com/rodo95coder/server-central-data.git
            force-pull: true
   application:
      name: config-server
